version: '3'
services:
  web:
    build: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/:/app
    environment:
      RUST_BACKTRACE: 1
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_PASSWORD: example
  front:
    build: front
    ports:
      - "3000:3000"
    volumes:
      - ./front/node_modules:/app/node_modules
